const products = [
  {
    product_id: 1,
    name: "mouse",
    description: "chuot may tinh",
    price: 10,
    image: ["casepc.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "mouse1",
    date_in: "1/6/2023",
    date_out: "1/7/2023",
    category: 4,
  },
  {
    product_id: 2,
    name: "USB 2.0",
    description: "luu tru du lieu di dong",
    price: 18,
    image: ["bag1.jpg", "bag1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "usb1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
  },
  {
    product_id: 3,
    name: "pc1",
    description: "case may tinh",
    price: 100,
    image: [
      "taycamchoigame.jpg",
      "usb1.jpg",
      "casepc.jpg",
      "sandisk.jpg",
      "ssd1.jpg",
    ],
    quantity_stock: 1000,
    product_code: "case1",
    date_in: "1/7/2023",
    date_out: "1/8/2023",
    category: 2,
  },
  {
    product_id: 4,
    name: "day nguon",
    description: "day nguon may tinh",
    price: 5,
    image: ["daynguon.jpg", "loa1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "daynguon1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
  },
  {
    product_id: 5,
    name: "sandisck",
    description: "o cung luu tru du lieu",
    price: 16,
    image: ["ram-1.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "usb2",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
  },
  {
    product_id: 6,
    name: "o cung ssd",
    description: "o cung luu tru du lieu",
    price: 38,
    image: ["usb2.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "ssd1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
  },
  {
    product_id: 7,
    name: "tay cam choi game",
    description: "tay cam choi game ps4",
    price: 58,
    image: [
      "limit-product-1.jpg",
      "usb1.jpg",
      "casepc.jpg",
      "sandisk.jpg",
      "ssd1.jpg",
    ],

    quantity_stock: 1000,
    product_code: "taycamchoigame1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 4,
  },
  {
    product_id: 8,
    name: "laptop acer",
    description: "laptop acer",
    price: 120,
    image: ["laptop2.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "laptop1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 3,
  },
];
// listCart = [
//   {
//     email: "vietwork2022@gmail.com",
//     cart: [
//       {
//         product_id: 8,
//         name: "laptop acer",
//         image: "limit-product-1.jpg",
//         price: 120,
//         quantity: 2,
//       },
//       {
//         product_id: 7,
//         name: "tay cam choi game",
//         price: 58,
//         image: "laptop2.jpg",
//         quantity: 2,
//       },
//     ],
//     status: 0,
//   },
//   {
//     email: "vietwork2023@gmail.com",
//     cart: [
//       {
//         product_id: 5,
//         name: "sandisck",
//         image: "ram-1.jpg",
//         price: 16,
//       },
//       {
//         product_id: 1,
//         name: "mouse",
//         price: 10,
//         image: "casepc.jpg",
//         quantity: 10,
//       },
//     ],
//     status: 0,
//   },
// ];
const productsIndex = [
  {
    product_id: 1,
    name: "mouse",
    description: "chuot may tinh",
    price: 10,
    image: ["casepc.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "mouse1",
    date_in: "1/6/2023",
    date_out: "1/7/2023",
    category: 4,
  },
  {
    product_id: 2,
    name: "USB 2.0",
    description: "luu tru du lieu di dong",
    price: 18,
    image: ["bag1.jpg", "bag1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "usb1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
  },
  {
    product_id: 3,
    name: "pc1",
    description: "case may tinh",
    price: 100,
    image: [
      "taycamchoigame.jpg",
      "usb1.jpg",
      "casepc.jpg",
      "sandisk.jpg",
      "ssd1.jpg",
    ],
    quantity_stock: 1000,
    product_code: "case1",
    date_in: "1/7/2023",
    date_out: "1/8/2023",
    category: 2,
  },
  {
    product_id: 4,
    name: "day nguon",
    description: "day nguon may tinh",
    price: 5,
    image: ["daynguon.jpg", "loa1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "daynguon1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
  },
  {
    product_id: 5,
    name: "sandisck",
    description: "o cung luu tru du lieu",
    price: 16,
    image: ["ram-1.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "usb2",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
  },
  {
    product_id: 6,
    name: "o cung ssd",
    description: "o cung luu tru du lieu",
    price: 38,
    image: ["usb2.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "ssd1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
  },
  {
    product_id: 7,
    name: "tay cam choi game",
    description: "tay cam choi game ps4",
    price: 58,
    image: [
      "limit-product-1.jpg",
      "usb1.jpg",
      "casepc.jpg",
      "sandisk.jpg",
      "ssd1.jpg",
    ],

    quantity_stock: 1000,
    product_code: "taycamchoigame1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 4,
  },
  {
    product_id: 8,
    name: "laptop acer",
    description: "laptop acer",
    price: 120,
    image: ["laptop2.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "laptop1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 3,
  },
];
localStorage.setItem("products", JSON.stringify(products));
// localStorage.setItem("listCart", JSON.stringify(listCart));
