const products = [
  {
    product_id: 1,
    name: "mouse",
    description: "chuot may tinh",
    price: 10,
    old_price: 5,
    image: ["casepc.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "mouse1",
    date_in: "1/6/2023",
    date_out: "1/7/2023",
    category: 4,
    new: true,
  },
  {
    product_id: 2,
    name: "USB 2.0",
    description: "luu tru du lieu di dong",
    price: 18,
    old_price: 30,
    image: ["bag1.jpg", "bag1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "usb1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
    new: true,
  },
  {
    product_id: 3,
    name: "pc1",
    description: "case may tinh",
    price: 100,
    old_price: 75,
    image: [
      "taycamchoigame.jpg",
      "usb1.jpg",
      "casepc.jpg",
      "sandisk.jpg",
      "ssd1.jpg",
    ],
    quantity_stock: 1000,
    product_code: "case1",
    date_in: "1/7/2023",
    date_out: "1/8/2023",
    category: 2,
    best_deal: true,
  },
  {
    product_id: 4,
    name: "day nguon",
    description: "day nguon may tinh",
    price: 5,
    old_price: 3,
    image: ["daynguon.jpg", "loa1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "daynguon1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
    best_deal: true,
  },
  {
    product_id: 5,
    name: "sandisck",
    description: "o cung luu tru du lieu",
    price: 16,
    old_price: 12,
    image: ["ram-1.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "usb2",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
    best_deal: true,
  },
  {
    product_id: 6,
    name: "o cung ssd",
    description: "o cung luu tru du lieu",
    price: 38,
    old_price: 25,
    image: ["usb2.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "ssd1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
    best_deal: true,
  },
  {
    product_id: 7,
    name: "tay cam choi game",
    description: "tay cam choi game ps4",
    price: 58,
    old_price: 89,
    image: [
      "limit-product-1.jpg",
      "usb1.jpg",
      "casepc.jpg",
      "sandisk.jpg",
      "ssd1.jpg",
    ],

    quantity_stock: 1000,
    product_code: "taycamchoigame1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 4,
  },
  {
    product_id: 8,
    name: "laptop acer",
    description: "laptop acer",
    price: 120,
    old_price: 125,
    image: ["laptop2.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "laptop1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 3,
  },
  {
    product_id: 9,
    name: "mouse",
    description: "chuot may tinh",
    price: 15,
    old_price: 18,
    image: ["casepc.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "mouse1",
    date_in: "1/6/2023",
    date_out: "1/7/2023",
    category: 4,
    sell: true,
    best_deal: true,
  },
  {
    product_id: 10,
    name: "USB 2.0",
    description: "luu tru du lieu di dong",
    price: 18,
    image: ["bag1.jpg", "bag1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "usb1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
    sell: true,
  },
  {
    product_id: 11,
    name: "pc1",
    description: "case may tinh",
    price: 100,
    old_price: 89,
    image: [
      "taycamchoigame.jpg",
      "usb1.jpg",
      "casepc.jpg",
      "sandisk.jpg",
      "ssd1.jpg",
    ],
    quantity_stock: 1000,
    product_code: "case1",
    date_in: "1/7/2023",
    date_out: "1/8/2023",
    category: 2,
    sell: true,
  },
  {
    product_id: 12,
    name: "day nguon",
    description: "day nguon may tinh",
    price: 5,
    old_price: 4,
    image: ["daynguon.jpg", "loa1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "daynguon1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
    sell: true,
  },
  {
    product_id: 13,
    name: "sandisck",
    description: "o cung luu tru du lieu",
    price: 16,
    image: ["ram-1.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "usb2",
    date_in: "1/9/2023",
    old_price: 14,
    date_out: "1/10/2023",
    category: 1,
    sell: true,
  },
  {
    product_id: 14,
    name: "o cung ssd",
    description: "o cung luu tru du lieu",
    price: 38,
    image: ["usb2.jpg", "usb1.jpg", "casepc.jpg", "sandisk.jpg"],
    quantity_stock: 1000,
    product_code: "ssd1",
    date_in: "1/9/2023",
    date_out: "1/10/2023",
    category: 1,
    sell: true,
    old_price: 35,
  },
];
localStorage.setItem("products", JSON.stringify(products));

// listCart = [
//   {
//     email: "vietwork2022@gmail.com",
//     cart: [
//       {
//         product_id: 8,
//         name: "laptop acer",
//         image: "limit-product-1.jpg",
//         price: 120,
//         quantity: 2,
//       },
//       {
//         product_id: 7,
//         name: "tay cam choi game",
//         price: 58,
//         image: "laptop2.jpg",
//         quantity: 2,
//       },
//     ],
//     status: 0,
//   },
//   {
//     email: "vietwork2023@gmail.com",
//     cart: [
//       {
//         product_id: 5,
//         name: "sandisck",
//         image: "ram-1.jpg",
//         price: 16,
//       },
//       {
//         product_id: 1,
//         name: "mouse",
//         price: 10,
//         image: "casepc.jpg",
//         quantity: 10,
//       },
//     ],
//     status: 0,
//   },
// ];

//checkout

let checkout = [
  {
    id: "id oder",
    email_user: "email nguoi mua",
    date: "ngay mua",
    listProduct: [
      {
        idProduct: "id san pham",
        quantity: "so luong san pham",
        price: "gia san pham",
      },
    ],
    total: "tong gia",
    status: "mac dinh la 0 : chua mua",
  },
];

//LIST USER
const list = [
  {
    email: "vietvo@gmail.com",
    address: "quang binh",
    name: "viet",
    password: "123456",
    phone: "0354909360",
    status: "active",
  },
  {
    email: "haduyhuan@gmail.com",
    address: "da nang",
    name: "anh",
    password: "123456",
    phone: "0354909360",
    status: "block",
  },
  {
    email: "lethibich@gmail.com",
    address: "quang nam",
    name: "bich",
    password: "123456",
    phone: "0354909360",
    status: "active",
  },
];

localStorage.setItem("listUsers", JSON.stringify(list));
